import pytest
import asyncio
from fastapi.testclient import TestClient
from src.api.main import app
from src.api.replay import replay_manager

client = TestClient(app)

def test_health():
    response = client.get("/api/v1/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"

def test_mode():
    response = client.get("/api/v1/mode")
    assert response.status_code == 200
    data = response.json()
    assert data["current_mode"] == "REPLAY"
    assert data["live_available"] == True

    # Try to set LIVE
    response = client.post("/api/v1/mode?mode=LIVE")
    assert response.status_code == 200
    assert response.json()["mode"] == "LIVE"

    # Try to set REPLAY
    response = client.post("/api/v1/mode?mode=REPLAY")
    assert response.status_code == 200
    assert response.json()["mode"] == "REPLAY"

def test_analyze():
    response = client.post("/api/v1/analyze", json={"text": "Apple is doing great this quarter!"})
    assert response.status_code == 200
    data = response.json()
    assert "signal_id" in data
    assert data["sentiment_label"] in ["positive", "neutral"]
    assert data["provenance"] == "MANUAL"

@pytest.mark.asyncio
async def test_replay_flow():
    # Stop and reset just in case
    client.post("/api/v1/replay/reset")
    
    # 1. Start Replay
    response = client.post("/api/v1/replay/start?speed=100.0") # Fast replay
    assert response.status_code == 200
    
    # Check status
    response = client.get("/api/v1/replay/status")
    assert response.json()["status"] == "running"
    
    # Wait a tiny bit for the background task to process a few records
    await asyncio.sleep(2.0)
    
    # Pause
    client.post("/api/v1/replay/pause")
    
    # Get signals to see if it generated anything
    response = client.get("/api/v1/signals")
    assert response.status_code == 200
    signals = response.json()
    assert len(signals) > 0, "No signals generated by replay!"
    
    # Check that at least one of the recent signals is REPLAY (since we share db with LIVE manual test)
    assert any(s["provenance"] == "REPLAY" for s in signals), "No REPLAY signal found in recent signals"
    
    # Check stress runs (some of the signals should have triggered a run)
    response = client.get("/api/v1/stress/runs")
    assert response.status_code == 200
    runs = response.json()
    
    if len(runs) > 0:
        # Validate run schema
        run = runs[0]
        assert "absolute_loss" in run
        assert run["run_mode"] in ["auto", "manual", "live"]
    
    # Test individual retrieval
    signal_id = signals[0]["signal_id"]
    response = client.get(f"/api/v1/signals/{signal_id}")
    assert response.status_code == 200
    assert response.json()["signal_id"] == signal_id

    # Stop and Reset
    client.post("/api/v1/replay/reset")
    response = client.get("/api/v1/replay/status")
    assert response.json()["status"] == "stopped"
    assert response.json()["processed_count"] == 0

def test_dashboard_overview():
    response = client.get("/api/v1/dashboard/overview")
    assert response.status_code == 200
    data = response.json()
    assert "total_signals" in data
    assert "total_stress_runs" in data
    assert "portfolio_value" in data
